platform :ios, "7.0"

pod 'MBProgressHud', '~> 0.8.0'
pod 'MMRecord', '~> 1.4.0'
pod 'MagicalRecord', '~> 2.2.0'
pod 'AFNetworking', '~> 2.1.0'
pod 'MMDrawerController/MMDrawerVisualStates', '~> 0.5.3'
